### ISSUE TITLE
Database error when previewing a question

### ISSUE THREAD

**Issue by mudrd8mz** [ysrivast2000/moodle-qtype_shortanssimilarity#1]
While testing the functionality, I had a simple question with automatic marking and eventually I received the following DB error:

```
More information about this error
Debug info: ERROR: null value in column "result" violates not-null constraint
DETAIL: Failing row contains (1, 60, foo bar, en, null, 1, 0).
UPDATE m_qtype_shortanssimilarity SET questionid = $1,key_text = $2,item_language = $3,result = $4,finished = $5,manual_grading = $6 WHERE id=$7
[array (
'questionid' => '60',
'key_text' => 'foo bar',
'item_language' => 'en',
'result' => NULL,
'finished' => 1,
'manual_grading' => '0',
0 => '1',
)]
Error code: errorprocessingresponses
Stack trace:

    line 498 of /lib/setuplib.php: moodle_exception thrown
    line 198 of /question/preview.php: call to print_error()

Output buffer: <br /> <b>Notice</b>: Trying to get property 'similarity' of non-object in <b>/question/type/shortanssimilarity/question.php</b> on line <b>307</b><br />
```

**Comment by SeekerHub** [comment]
@mudrd8mz 
Solution:
- The DB error popped up as the wrong service bridge URL  was called and the required parameters were not satisfied. Now its been corrected.
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/ba4633cbce7d6b290ab1eef0d866b735cee3bb70/question.php#L312

- Also the spelling of "DEFAULT" was wrong and now it's been corrected. Here is one of them.
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/ba4633cbce7d6b290ab1eef0d866b735cee3bb70/db/install.xml#L13
