### ISSUE TITLE
No need to explicitly load classes located under classes folder

### ISSUE THREAD

**Issue by mudrd8mz** [ysrivast2000/moodle-qtype_shortanssimilarity#2]
If they are well named, then classes defined in files under the "classes" folder are auto-loaded. They should not be required and loaded manually as in https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/3c380d4e463a86a5378c86453dfadb9914c3f2b3/question.php#L28

**Comment by SeekerHub** [comment]
Solutions:
- Brought out the `calculator.php` directly under the `classes` folder and using the right namespace inside it.
 https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/f6e94362a3282b3992934749fb87e46dcf993dbe/question.php#L25

**Comment by SeekerHub** [comment]
@mudrd8mz 
Solution:
- Brought the `calculator.php` directly under the `classes` folder and assigning the right namespace inside the file.
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/f6e94362a3282b3992934749fb87e46dcf993dbe/classes/calculator.php#L25

- The Line which was used to call `calculator.php` was removed and the object of the calculator class can be created directly as the classes are autoloaded.
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/f6e94362a3282b3992934749fb87e46dcf993dbe/question.php#L256
