### ISSUE TITLE
Missing Privacy API

### ISSUE THREAD

**Issue by danmarsden** [ysrivast2000/moodle-qtype_shortanssimilarity#3]
As mentioned in https://tracker.moodle.org/browse/CONTRIB-8479, 

Privacy API must be implemented as the plugin integrates with an external system. Plugin must not gather, store, process or share personal data beyond what is required for its functionality. In this case, it seems that no personal data are shared. But admins need to know, and that is what Privacy API is for.

Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

More information on the privacy class is here:
https://docs.moodle.org/dev/Privacy_API

Please note, as David mentions this is a blocker for approval in the plugins db.

**Comment by SeekerHub** [comment]
@danmarsden 
Privacy API implemented, thank you.

https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/commit/9e525ac6671f5e6cc84764355702919d957f3d54

**Comment by maiga-vip** [comment]
@danmarsden Hi Dan, we cannot add comment to notify you at https://tracker.moodle.org/browse/CONTRIB-8479 but only can @ you here. We have done all the issues you mentioned on July 10 (include this one). Hope you could allow to close these issues. Thank you so much in advance.

**Comment by danmarsden** [comment]
You should close issues yourself when you have resolved them. The tracker site does not share accounts with moodle.org, please create an account in the tracker site and comment in the tracker (we expect moodle plugin developers to have an account in the moodle tracker site.) Thanks!

**Comment by maiga-vip** [comment]
Thank you so much, @danmarsden. I will then close the issue here as well as create an account on the tracker site.
