### ISSUE TITLE
settings.php and styles.css are empty

### ISSUE THREAD

**Issue by danmarsden** [ysrivast2000/moodle-qtype_shortanssimilarity#4]
as mentioned in https://tracker.moodle.org/browse/CONTRIB-8479

You are better to delete these empty files - they are not required, and leaving empty files in place could cause other issues.

**Comment by danmarsden** [comment]
also the files in /tests should be removed they aren't actually performing any tests.

**Comment by SeekerHub** [comment]
@danmarsden 
- Some file that was not in use under the test folder was removed.
- Settings.php and styles.css were also removed as they were empty.
