### ISSUE TITLE
Does not support recent versions of Moodle

### ISSUE THREAD

**Issue by danmarsden** [ysrivast2000/moodle-qtype_shortanssimilarity#5]
as mentioned in CONTRIB-8749

The plugin must support recent Moodle versions. The only declared supported Moodle version is 3.5 which is quite old now - you must make sure your plugin supports at least 3.9 and higher before we could consider approving this in the plugins db.

**Comment by SeekerHub** [comment]
@danmarsden 
With reference to the above issue, I made the following change in the version.php file. Can you please guide me if I need any further changes or having this resolves the version support issue?
Thank you so much.
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/cc9205558b8a0dd8966775e090d428a6fb4455e9/version.php#L31

**Comment by danmarsden** [comment]
I think you misunderstood. When you upload a plugin you set the supported versions in the form. You had only selected 3.5 which suggested that you had only tested it in 3.5. If it works and you have tested in newer versions you need to set those when you upload in the plugins db

**Comment by SeekerHub** [comment]
Thank you for the clarification!

**Comment by SeekerHub** [comment]
@danmarsden 
Thank you so much! we have resubmitted our Moodle plugin(ShortAnswer Similarity) for approval.
Here's a screenshot of the submission.

![submission](https://user-images.githubusercontent.com/49167120/129674221-9d76d88b-8e16-4ab7-ae11-664e77514f69.png)

**Comment by maiga-vip** [comment]
Thank you so much, @danmarsden. I will then close the issue here.
