### ISSUE TITLE
file_get_content for external urls will not work in all sites

### ISSUE THREAD

**Issue by danmarsden** [ysrivast2000/moodle-qtype_shortanssimilarity#7]
Many Moodle systems will sit behind a proxy - preventing their web-server from making outgoing web requests - you should be using the Moodle api download_file_content or using the Moodle "curl" class instead of making direct calls to file_get_content here:
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/main/classes/calculator.php#L81

**Comment by danmarsden** [comment]
same thing here:
https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/blob/main/question.php#L312

**Comment by SeekerHub** [comment]
@danmarsden 
Thank you for pointing out, I have made the necessary changes.
As mentioned I am using `curl` instead if `file_get_contents`.

https://github.com/ysrivast2000/moodle-qtype_shortanssimilarity/commit/f23c793b4086cbdbbd3e7d3bde1e0b12ac3aef25#diff-4efefc18e9b32a87b94a57e2e517149f29475531e3a9ad7169148a50d76c5be0

**Comment by maiga-vip** [comment]
Thank you so much, @danmarsden. I will then close the issue here.
